# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Roxy < Formula
  desc "Dev server port multiplexer with subdomain routing"
  homepage "https://github.com/logscore/roxy"
  version "1.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/logscore/roxy/releases/download/v1.2.0/roxy_darwin_amd64.tar.gz"
      sha256 "1659f2acc0083b7303c2b59f218f5e27b7c65bb13d7e2c60234c8f9d31884477"

      define_method(:install) do
        bin.install "roxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/logscore/roxy/releases/download/v1.2.0/roxy_darwin_arm64.tar.gz"
      sha256 "8f3079849fd5a8089150a61dfe3be8bc3726c809670e4e803fd9c362027f130e"

      define_method(:install) do
        bin.install "roxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/logscore/roxy/releases/download/v1.2.0/roxy_linux_amd64.tar.gz"
      sha256 "51a952d6bdaf2c8e748c840fb8ba3e7eb8956e5205285016d750edd67d45348b"
      define_method(:install) do
        bin.install "roxy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/logscore/roxy/releases/download/v1.2.0/roxy_linux_arm64.tar.gz"
      sha256 "b64bd8130c26c6698d9afc162c2fed02f05d780094b9a1f9cc7f0a3919c667d8"
      define_method(:install) do
        bin.install "roxy"
      end
    end
  end
end
