# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Roxy < Formula
  desc "Dev server port multiplexer with subdomain routing"
  homepage "https://github.com/logscore/roxy"
  version "1.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/logscore/roxy/releases/download/v1.2.1/roxy_darwin_amd64.tar.gz"
      sha256 "ca72b5b164d6cf93f6c9430f847073a9de725cb31902ac6eda68a2838d8fda47"

      define_method(:install) do
        bin.install "roxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/logscore/roxy/releases/download/v1.2.1/roxy_darwin_arm64.tar.gz"
      sha256 "5bc6325e86694275056bf670a239f6a66ff8ccb15e678cf9a8556dbe339075cf"

      define_method(:install) do
        bin.install "roxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/logscore/roxy/releases/download/v1.2.1/roxy_linux_amd64.tar.gz"
      sha256 "358364ef28d2f037ed03b55420f840f2e1ce938eef3096d0276c6e6c1d368c25"
      define_method(:install) do
        bin.install "roxy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/logscore/roxy/releases/download/v1.2.1/roxy_linux_arm64.tar.gz"
      sha256 "a8b7d7ea783bea135942a6100c1481639f98e2adaa1c25aa71e8fa0c9f01e34d"
      define_method(:install) do
        bin.install "roxy"
      end
    end
  end
end
